### ISSUE TITLE
Bazel protoc Rules for gqlgencfg and gql

### ISSUE THREAD

**Issue by sateeshpnv** [danielvladco/go-proto-gql#15]
Are there bazel protoc rules to generate gqlgencfg and gql?

gogqlgen is straight-forward because it generates a .go file and we can use [go_proto_compiler](https://github.com/bazelbuild/rules_go/blob/master/proto/core.rst#go-proto-compiler) from bazel rules_go. gqlgencfg and gql generate .yml and .graphqls file respectively and [require a custom bazel protoc rules](https://github.com/bazelbuild/rules_go/issues/2540) to generate gqlgencfg and gql.

Checking if such rules exist already.

**Comment by danielvladco** [comment]
At the moment no, but I noticed someone added it in a fork
https://github.com/romnnn/go-proto-gql

**Comment by sateeshpnv** [comment]
Thanks for responding.

Those are to build go-proto-gql. gazelle pretty much does it.

Is there any bazel rule that invokes protoc using protoc-gen-gql plugin?

**Comment by danielvladco** [comment]
No, bazel is not supported.

Look into this fork https://github.com/romnnn/go-proto-gql might be what you need
