### ISSUE TITLE
dependencies doesn't work when we give output directories different for --gogqlgen_out and --go_out

### ISSUE THREAD

**Issue by Vysyarajusantosh** [danielvladco/go-proto-gql#16]
First of all I would like to thank you for your work.

While I was using your library I see dependency disconnect when we give output directories different for --gogqlgen_out and --go_out. Will it be possible to look into this issue?

I am using below command in my case.

protoc \
--go_out=plugins=grpc,paths=source_relative:./example/pb \
--dart_out=grpc:./example/dart_pb \
--gqlgencfg_out=paths=source_relative:./example/yml_files \
--gql_out=svcdir=true,paths=source_relative:./example/schemas \
--gogqlgen_out=paths=source_relative,gogoimport=false:./example/services \
-I=. -I=./example/ example/proto/*.proto

**Comment by danielvladco** [comment]
Hi,

I will look into it, for now you can use `M` option to map proto imorts to the right ones. For example: `protoc --gogo_out=paths=source_relative,Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor:./pb `

**Comment by danielvladco** [comment]
Closing for now. If you experience the same problem please open a new issue. Hope the recent refactor fixed it.
