### ISSUE TITLE
use another validator

### ISSUE THREAD

**Issue by vtolstov** [danielvladco/go-proto-gql#2]
what do you think about https://github.com/envoyproxy/protoc-gen-validate ?

**Comment by danielvladco** [comment]
Hi @vtolstov,

I actually thought about it some time ago, and removed the validator. It is not needed and adds extra  dependencies. Now in the latest version `v0.6.1` it uses `(gql.field.required) = true` option instead

**Comment by vtolstov** [comment]
this is fine news, thanks!

**Comment by vtolstov** [comment]
hm, when i'm try to use option i have error that option does not known

**Comment by danielvladco** [comment]
Hi @vtolstov,

Sorry I showed you a wrong example.. `string id = 1 [(gql.field) = {required: true}];` this should work.

Also please make sure you use version `v0.6.1`. For more examples please consult the `/examples` folder.

**Comment by vtolstov** [comment]
yes, this works
