### ISSUE TITLE
Does the gateway support grpc streams ?

### ISSUE THREAD

**Issue by elkaps** [danielvladco/go-proto-gql#21]
I tried running a subscription for a (server) grpc stream with the graphql playground but I get the following error:
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:8080/playground. Please check if the endpoint url is correct."
}
```

**Comment by danielvladco** [comment]
Hello @elkaps , the gateway does not support subscriptions yet. Gateway is still very alpha. It supports only mutations. Also the queries do not run in parallel. 

Instead of using the Gateway use graphql code generation, to generate Graphql schema and golang bindings to grpc code.

**Comment by elkaps** [comment]
Thanks for the info! I will use the code generation. The gateway is an awesome feature though :)
