### ISSUE TITLE
Protobuf with 'oneof' creates invalid schema with directive.

### ISSUE THREAD

**Issue by westongcooper** [danielvladco/go-proto-gql#22]
Given this protobuf I'm not able to create a valid schema file.  
```
syntax = "proto2";

package user.Profile;

message Value {
  oneof _propertyReference {
    string   propertyId = 2;
    Property property   = 3;
  }

  optional string id    = 1;
  required string value = 4;
}

message Property {
  optional string id      = 1;
  required string label   = 2;
}

message UserProfileExtended {
  repeated Value items = 1;
}

message UserProfile {
  optional UserProfileExtended  extended  = 4;
}

service UserProfileService {
    rpc upsert (UserProfileUpsertRequest) returns (UserProfile);
}

message UserProfileUpsertRequest {
    required UserProfile profile  = 3;
}
```

With this protobuf I was able to generate the schema below

```
directive @UserProfileService on FIELD_DEFINITION
directive @Value_PropertyReference on INPUT_FIELD_DEFINITION
type Mutation {
	userProfileServiceUpsert(in: UserProfileUpsertRequestInput): UserProfile
}
type Property {
	id: String
	label: String
}
input PropertyInput {
	id: String
	label: String
}
type Query {
	dummy: Boolean
}
type UserProfile {
	extended: UserProfileExtended
}
type UserProfileExtended {
	items: [Value!]
}
input UserProfileExtendedInput {
	items: [ValueInput!]
}
input UserProfileInput {
	extended: UserProfileExtendedInput
}
input UserProfileUpsertRequestInput {
	profile: UserProfileInput
}
type Value {
	xPropertyReference: Value_PropertyReference
	id: String
	value: String
}
input ValueInput {
	propertyId: String @Value_PropertyReference
	property: PropertyInput @Value_PropertyReference
	id: String
	value: String
}
type Value_Property {
	property: Property
}
type Value_PropertyId {
	propertyId: String
}
union Value_PropertyReference = Value_PropertyId | Value_Property
```

Being that `UserProfile` is the request object for `userProfileServiceUpsert` wouldn't the `ValueInput` also only expect either `propertyId` or the `property` type.  It's not clear what the directive is doing or trying to do.

**Comment by danielvladco** [comment]
The problem is that graphql input objects are way more simple than type objects. An input can have as a field only: a scalar, an enum or another input. An input field cannot be union or interface. 

So instead of having `xPropertyReference` I flattened the `oneof` fields into the parent structure and addend a symbolic directive suggesting that only one of those 2 fields can be used at the same time. 

You can use that directive to validate on the server side that only one field is passed.

**Comment by westongcooper** [comment]
I realized my problem here.  When the schema is generated with the protobuf there is a naming conflict with the union type `Value_PropertyReference` and the directive `@Value_PropertyReference`.  When using the `@graphql-tools` library to load the schema since the names are identical there is a merge error trying to merge the schema. [SOURCE](https://github.com/ardatan/graphql-tools/blob/dfd900577c9331952a4588191771d2dc2e5174a9/packages/merge/src/typedefs-mergers/merge-nodes.ts#L24)

Is it possible to have a different name for the directive?

**Comment by danielvladco** [comment]
that's interesting, directives shouldn't conflict with other type names... I think this is an issue with @graphql-tools. 

It will probably be a good feature to add a prefix to your directives. You can open another issue for this feature.

**Comment by artificial-aidan** [comment]
Also running into this issue. The generated schema has a union and a directive with the same name.

```
directive @Value_PropertyReference on INPUT_FIELD_DEFINITION

union Value_PropertyReference = Value_PropertyId | Value_Property
```

Aren't the directive and types created by this tool?
