### ISSUE TITLE
Trying to understand how the example codegen works

### ISSUE THREAD

**Issue by rufman** [danielvladco/go-proto-gql#23]
Running the example codegen I get `directive Query is not implemented` when running:
```
query {
  queryQuery2(in: {
    stringX: "hello",
    foo: {
      param1: "bar"
    }
    double: 32
  }) {
    string2
  }
}
```
Am I missing something here?

**Comment by danielvladco** [comment]
Can you provide more details? 
If are you using the gateway then this is expected since the gateway is in very early stages of development and doesn't implement graphql queries yet. As of right now graphql gateway implements only the mutations.
