### ISSUE TITLE
protobuf.struct issues generating input

### ISSUE THREAD

**Issue by bstanescu** [danielvladco/go-proto-gql#26]
```protobuf
syntax = "proto3";

package test;

import "google/protobuf/struct.proto";

message Foo {
  string id = 1;
  google.protobuf.Struct bar = 2;
}

message FooRequest {
  Foo foo = 1;
}

message FooResponse {}

service AuditService {
  rpc Baz(FooRequest) returns (FooResponse) {}
}
```

It seems that the `ListValueInput` generated from [ListValue](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto#L92-L95) has trouble compiling to graphql (I stripped away the comments for readability)

```graphql
directive @AuditService on FIELD_DEFINITION
directive @ValueKind on INPUT_FIELD_DEFINITION
input FooInput {
	id: String
	bar: StructInput
}
input FooRequestInput {
	foo: FooInput
}
input ListValueInput
type Mutation {
	auditServiceBaz(in: FooRequestInput): Boolean
}
enum NullValue {
	NULL_VALUE
}
type Query {
	dummy: Boolean
}
input StructInput {
	fields: [Struct_FieldsEntryInput!]
}
input Struct_FieldsEntryInput {
	key: String
	value: ValueInput
}
input ValueInput {
	nullValue: NullValue @ValueKind
	numberValue: Float @ValueKind
	stringValue: String @ValueKind
	boolValue: Boolean @ValueKind
	listValue: ListValueInput @ValueKind
}

```

**Comment by danielvladco** [comment]
Hi Bogdan, Thanks, for reporting
I will try to fix this over weekend

Please provide all the relevant proto files, I cannot understand where the ListValue comes from

**Comment by bstanescu** [comment]
Thank you! The imported proto file is from google's struct.proto (link is on the [ListValue](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto#L92-L95) above), pasting here for reference:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto

**Comment by danielvladco** [comment]
Hi @bstanescu, I discovered the issue, but didn't have time to fix it yet.

The problem is that message ListValue has circular dependency and looks like the code does't handle that well

**Comment by danielvladco** [comment]
Pushed the fix on `v0.8.2`

**Comment by danielvladco** [comment]
Hi @bstanescu, if you no longer experience this issue please close it

**Comment by bstanescu** [comment]
Thank you! I will try today and let you know.

**Comment by bstanescu** [comment]
Works great. 💯 Sorry about the delay in confirming this.
Thanks! 👍
