### ISSUE TITLE
error when options rpc_type and svc_type are not explicitly defined

### ISSUE THREAD

**Issue by vtolstov** [danielvladco/go-proto-gql#3]
```
protoc-gen-gogql: plugin.go:419: :proto: missing extension
--gogqlgen_out: protoc-gen-gogqlgen: Plugin failed with status code 1.
```

**Comment by danielvladco** [comment]
Hi @vtolstov ,

Could you please provide more info on how to reproduce the issue?

Contents of .proto file?
What is the bash command?

**Comment by vtolstov** [comment]
file contents: https://gist.github.com/vtolstov/560e450d9fe67c02c5ea60799427d93f
bash cmd: protoc -I/home/vtolstov/.cache/go-path/src -I/home/vtolstov/devel/projects/centralv2/proto -I/home/vtolstov/.cache/go-path/src/github.com/envoyproxy/protoc-gen-validate -I/home/vtolstov/devel/projects/centralv2/vendor -I/home/vtolstov/devel/projects/centralv2 -I. --gogqlgen_out=gogoimport=false:. zone.proto

**Comment by danielvladco** [comment]
Hi @vtolstov ,

Sorry i Could not reproduce the issue. I used a minimal schema only with gql related annotations.

```proto
syntax = "proto3";
package unistack;
option go_package = "unistackpb";
import "github.com/danielvladco/go-proto-gql/pb@v0.6.1/gql.proto";
service ZoneService {
  rpc List(ZoneListReq) returns (ZoneListRsp) {option (gql.rpc_type) = QUERY;}
};

message ZoneListReq {}
message ZoneListRsp {}
```

The schema you showed is too complex there may be a lot of points of failure. Also the error in the console is showing a generic protobuf error. Look here for more details https://github.com/golang/protobuf/blob/master/proto/extensions.go

I advise you to upgrade to latest version v0.6.1 and check if the issue still persists.

**Comment by vtolstov** [comment]
option (gql.rpc_type) = QUERY; may be i miss to specify rpc type for each  method.
Do you skip methods without such annotation?

**Comment by danielvladco** [comment]
No, the default method type is MUTATION so if you don't specify the rpc_type it will be mutation by default.

**Comment by vtolstov** [comment]
After i'm specific rpc_type error changed to:
protoc-gen-gogql: plugin.go:197: WARN:  go import path for zone.proto could not be resolved correctly: use option go_package with full package name in this file
so i think that missing rpc_type bring previous error, now i think that i need to change import paths

**Comment by danielvladco** [comment]
Use `option go_package = "github.com/user/project;project";` rather than `option go_package = "project";` and when running command use 'paths=source_relative';

Please refer to this issue:
https://github.com/golang/protobuf/issues/515

The warning happens because it is problematic to determine the import path of the generated files. Especially now with go modules.

Regarding error when dot rpc_type in the other methods I am still investigating this issue.

**Comment by vtolstov** [comment]
nice, i can success generate files, but last error present like this:
```
proxy/unistack/unistackpb/zone.gqlgen.pb.go:19:2: imported and not used: "github.com/golang/protobuf/ptypes/empty" as github_com_golang_protobuf_ptypes_empty
proxy/unistack/unistackpb/zone.gqlgen.pb.go:27:43: undefined: ZoneServiceServer
```
github_com_golang_protobuf_ptypes_empty is not used in in generated file
also i don't have in pb files ZoneServiceServer i have ZoneService does it possible to change this interface name via annotations? I'm try to use generator with go-micro (https://github.com/micro/protoc-gen-micro) and it generate interface with ZoneService and not ZoneServiceServer

**Comment by vtolstov** [comment]
gentle ping...

**Comment by danielvladco** [comment]
Hi,

I will have to think about this feature. At the moment the library is not expected to work with micro but with the default grpc implementation. If you require this feature i guess you will have to fork the repo and add your custom implementation. It is not hart though. All you have to do is to delete the "Server" string at the end of this line https://github.com/danielvladco/go-proto-gql/blob/master/protoc-gen-gogqlgen/main.go#L106

**Comment by vtolstov** [comment]
thank you, now i'm simple create additional file inside generated path with needed interface (that equal to interface without Server string)

**Comment by vtolstov** [comment]
any chance to fix the issue ?
```
protoc-gen-gogql: plugin.go:419: :proto: missing extension
--gogqlgen_out: protoc-gen-gogqlgen: Plugin failed with status code 1.
```

this is because i don't specify rpc_type and default not working
No, the default method type is MUTATION so if you don't specify the rpc_type it will be mutation by default.

**Comment by godebug** [comment]
//go:generate protoc --gql_out=paths=source_relative:. -I=${GOPATH}/pkg/mod/ -I=. -I=./rpc/ base.proto

```
syntax = "proto3";
package rpc;
option go_package = "rpc";

service GEMS {
    rpc GetCompaign(CompaignRequest) returns (CompaignReply) {}
}

message CompaignRequest {
    int64 ID = 1;
    string Name = 2;
}

message CompaignReply {
    string message = 1;
}
```

**Comment by danielvladco** [comment]
Hi @godebug 
Yes there is a issue if you open braces and don't pass explicitly option rpc_type you receive this error
for now as a workaround you can write 
`rpc GetCompaign(CompaignRequest) returns (CompaignReply);` without braces

**Comment by danielvladco** [comment]
@godebug @vtolstov 
I released the fix with tag v0.7.3.
Can you check out if you still experience the issue?

**Comment by vtolstov** [comment]
i see it now after update to v0.7.3:
protoc-gen-gogql: plugin.go:419: :proto: missing extension
--gogqlgen_out: protoc-gen-gogqlgen: Plugin failed with status code 1.

**Comment by vtolstov** [comment]
my service looks like this:
```
service AccountService {                                                                                        
  rpc Lookup(AccountLookupReq) returns (Account) {                                                              
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = { operation_id: "AccountLookup"; };  
    option (google.api.http) = { get: "/api/unistack/v0/accounts/{uuid}" };                                     
  };                                                                                                            
```

**Comment by danielvladco** [comment]
@vtolstov 
It looks like you are still using the old binary.
Now at the https://github.com/danielvladco/go-proto-gql/blob/master/plugin/plugin.go#L419 isn't thrown any error.

Try the following commands from your command line:

`rm $(which protoc-gen-gogqlgen)`
`rm $(which protoc-gen-gql)`
`go get -u github.com/danielvladco/go-proto-gql/...`
`go install github.com/danielvladco/go-proto-gql/protoc-gen-gogqlgen`
`go install github.com/danielvladco/go-proto-gql/protoc-gen-gql`

**Comment by vtolstov** [comment]
yeah, sorry. all works fine now. thanks!
