### ISSUE TITLE
use own json marshaller/unmarshaller

### ISSUE THREAD

**Issue by vtolstov** [danielvladco/go-proto-gql#5]
Can you add ability to use own json marshaler/unmarshaler?
I'm prefer to use https://github.com/json-iterator/go, but somebody may wants jsonb.

**Comment by danielvladco** [comment]
Hi @vtolstov ,

The json package is used only for maps encode/decode as a workaround.
https://github.com/danielvladco/go-proto-gql/issues/4 in this issue I highly suggest not using maps with this plugin.

**Comment by vtolstov** [comment]
ok, thanks!
