### ISSUE TITLE
Is there possibility to filter types/services that should be generated in GraphQL?

### ISSUE THREAD

**Issue by mkorolyov** [danielvladco/go-proto-gql#9]
Hi, what if I need to filter declared Proto types and services for GraphQL? is it possible at the moment? If not will you accept PR with some tagging of needed types/services or another way marking what need to be generated?
thanks!

**Comment by danielvladco** [comment]
Hi @mkorolyov, at the moment it is not possible. Yes I will accept a PR if you are willing to implement it yourself.

**Comment by mnkg561** [comment]
@mkorolyov @danielvladco  I'm curious if you are able to find any workaround. i want to exclude some fields in the message (something like using tag `graphql:"_"` which can exclude certain fields or types from graphQL generation process)

**Comment by mkorolyov** [comment]
@mnkg561 Hey, i'm not using this generation at the moment but will definitely add PR with exclusion flags later, have some leak of time at the moment :)

**Comment by danielvladco** [comment]
Added ignore option to fields, services and fields in version v0.8.3
